#!/usr/bin/env bash

set -e

docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/main.o -c src/main.cpp -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb
docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/spell.o -c src/spell.cpp -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb
docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/loop_wrapper.o -c src/loop_wrapper.cpp -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb
docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/loop.o -c src/loop.cpp -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb
docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/rayhacks.o -c src/rayhacks.cpp -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb
docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/hitbox.o -c src/hitbox.cpp -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb
docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/assets.o -c src/assets.cpp -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb

docker run --rm -v "$(pwd):/src" emscripten/emsdk em++ -std=c++23 -o web-build/game.html ./web-build/*.o -Os -g -Wall ./web-build/libraylib.a -I. -I./raylib/src/ -L./raylib/src -Lweb-build/libraylib.a --preload-file assets -s USE_GLFW=3 -DPLATFORM_WEB --shell-file shell.html -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4gb
